### ISSUE TITLE
theme.js error

### ISSUE THREAD

**Issue by byouloh** [maxkostinevich/Chakra-UI-Admin-Dashboard-Template#4]
When I run it by "npm start", but I got the following error message from the browser console:

Uncaught TypeError: b is not a function
    at eval (theme.js:6:422)
    at Array.forEach (<anonymous>)
    at c (theme.js:6:402)
    at eval (theme.js:6:575)
    at Module../src/theme.js (main.js:2250:1)
    at __webpack_require__ (main.js:4516:33)
    at fn (main.js:4727:21)
    at eval (App.js:8:64)
    at Module../src/App.js (main.js:1920:1)
    at __webpack_require__ (main.js:4516:33)

**Comment by byouloh** [comment]
After I removed nodejs version 16.x and reinstalled version 14.x(14.8.x), this error never occurs. As I know "node-sass": "^6.0.1" and nodejs : 16.x compatible each other, this one is not from that, but from probably webpack version.

**Comment by byouloh** [comment]
After using "babel-loader" instead of "swc-loader" and returning "swc-loader", the same error comes. So, when I changed into "babel-loader" again, the problem disappeared. FYI.
